version: '3.9'

services:
  stt-audio-ws:
    build:
      context: ./stt/audio_ws
    container_name: stt-audio-ws
    ports:
      - "8001:8001"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - stt-audio-ws