version: '3.9'
services:
  stt:
    build: ./stt
    container_name: stt
    ports:
      - "8001:8000"

  llm:
    build: ./llm
    container_name: llm
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "8002:8000"

  tester:
    build:
      context: ./test
    container_name: tester
    ports:
      - "8082:8080"   # 필요하면 외부에서 접근하기 위해 열어둬도 되고
    volumes:
      - ./output:/app/output
    depends_on:
      - controller


  controller:
    build: ./controller
    container_name: controller
    ports:
      - "8080:8080"
    depends_on:
      - stt
      - llm


  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - controller
