version: '3.9'
services:
  stt:
    build: ./stt
    container_name: stt
    ports:
      - "8001:8000"

  llm:
    build: ./llm
    container_name: llm
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "8002:8000"

  tester:
    build: ./test
    container_name: tester
    ports:
      - "8085:8080"

  controller:
    build: ./controller
    container_name: controller
    ports:
      - "8080:8080"
    depends_on:
      - stt
      - llm
      - tester

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - controller
